org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.3-pre-2
minecraft_range=>=26.3- <26.4-

loader_version=0.19.5
loader_range=>=0.19.5

fabric_version=0.159.4+26.3
fabric_api_range=>=0.159.4

mod_version=1.1.0-26.3_test_pre-2

maven_group=cz.mcsworld.eroded
archives_base_name=eroded_world
