org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
minecraft_range=26.2

loader_version=0.19.2
loader_range=>=0.19.2

fabric_version=0.155.2+26.2
fabric_api_range=>=0.155.2

mod_version=1.1.0-26.2

maven_group=cz.mcsworld.eroded
archives_base_name=eroded_world
